import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navbar
    'nav.vision': 'Vision',
    'nav.platform': 'Platform',
    'nav.about': 'About',
    'nav.news': 'News',
    'nav.contact': 'Contact',
    'nav.volunteer': 'VOLUNTEER',
    
    // Hero Section
    'hero.tagline': 'LET\'S BUILD A NEW BANGLADESH',
    'hero.tagline.mobile': 'NEW BANGLADESH',
    'hero.name.first': 'NAHID',
    'hero.name.last': 'ISLAM',
    'hero.vision.link': 'See Our Vision',
    'hero.vision.link.mobile': 'Vision',
    'hero.vision.subtitle': 'Fight for a just and equitable society, or "Vote for a brighter tomorrow."',
    'hero.join': 'Join the',
    'hero.movement': 'Movement',
    'hero.badge.join': 'Join the',
    'hero.badge.movement': 'MOVEMENT',
    'hero.description.student': 'Student Leader.',
    'hero.description.leader': 'Revolutionary.',
    'hero.description.candidate': 'Convener of National Citizens Party (NCP).',
    'hero.independent': 'NATIONAL CITIZENS PARTY (NCP)',
    'hero.constituency': 'Dhaka-11',
    
    // Vision Section
    'vision.label': 'OUR VISION',
    'vision.title.new': 'A New',
    'vision.title.bangladesh': 'Bangladesh',
    'vision.title.starts': 'Starts Here',
    'vision.subtitle': 'Together, we will build a constituency that represents the voices of students, workers, and families who believe in transparent, accountable leadership.',
    'vision.card1.title': 'Justice & Equality',
    'vision.card1.desc': 'Building a society where every citizen has equal rights and opportunities',
    'vision.card2.title': 'Education Reform',
    'vision.card2.desc': 'Modernizing our education system to prepare students for the future',
    'vision.card3.title': 'Youth Empowerment',
    'vision.card3.desc': 'Creating pathways for young leaders to shape our nation',
    'vision.card4.title': 'Economic Growth',
    'vision.card4.desc': 'Supporting entrepreneurs and small businesses to build prosperity',
    'vision.card5.title': 'Healthcare Access',
    'vision.card5.desc': 'Ensuring quality healthcare is accessible to all communities',
    'vision.card6.title': 'Innovation Hub',
    'vision.card6.desc': 'Transforming Dhaka-10 into a center for technology and innovation',
    'vision.cta.label': 'READY TO MAKE A DIFFERENCE?',
    'vision.cta.title': 'Join our campaign today',
    'vision.cta.button': 'GET INVOLVED',

    // July Revolution Section
    'july.label': 'THE UPRISING',
    'july.title.the': 'The',
    'july.title.architect': 'Architect',
    'july.title.change': 'of Change',
    'july.subtitle': 'Led the Students Against Discrimination movement that sparked the July 2024 Revolution',
    'july.role.title': 'Key Coordinator',
    'july.role.desc': 'Led the Students Against Discrimination movement during the July Revolution',
    'july.movement.title': 'Mass Uprising',
    'july.movement.desc': 'From quota reform protest to a movement that changed history',
    'july.book.label': 'FROM THE FRONTLINES',
    'july.book.title': 'জুলাই: জন্মভূমি অথবা মৃত্যু (July: Motherland or Death)',
    'july.book.desc': 'A firsthand account of the uprising, detailing the struggle, sacrifice, and spirit of liberation that defined July 2024.',
    'july.book.cta': 'Read More',
    'july.quote.text': 'We will protect our borders ourselves. We will not tolerate any more aggression at the border.',
    'july.quote.author': 'Nahid Islam',
    'july.struggle.title': 'The Path of Sacrifice',
    'july.struggle.detention.title': 'Detention',
    'july.struggle.detention.desc': 'Faced unlawful detention while fighting for justice',
    'july.struggle.torture.title': 'Physical & Psychological Torture',
    'july.struggle.torture.desc': 'Endured extreme conditions for the cause',
    'july.struggle.surveillance.title': 'Heavy Surveillance',
    'july.struggle.surveillance.desc': 'Continued the movement despite constant monitoring',
    'july.struggle.liberation.title': 'People\'s Liberation',
    'july.struggle.liberation.desc': 'Achieved victory through collective sacrifice',

    // Public Service Section
    'service.label': 'PUBLIC SERVICE',
    'service.title.public': 'Public',
    'service.title.service': 'Service & Leadership',
    'service.subtitle': 'Served as Adviser in the Interim Government (Aug 2024 – Feb 2025), driving reforms across multiple ministries',
    'service.role1.title': 'Adviser for Posts, Telecommunications and Information Technology',
    'service.role1.period': 'August 2024 – February 2025',
    'service.role1.desc': 'Reduced taxes on mobile internet and services to make internet affordable for common people and worked to eliminate digital inequality',
    'service.role2.title': 'Adviser for Information and Broadcasting',
    'service.role2.period': 'August 2024 – February 2025',
    'service.role2.desc': 'Fundamentally reformed the long-standing censorship system in Bangladesh and established the \'Bangladesh Film Certification Board\' in response to filmmakers\' demands',
    'service.role3.title': 'Convener, National Citizens Party (NCP)',
    'service.role3.period': 'February 2025 – Present',
    'service.role3.desc': 'Resigned from government to form a new political party, currently preparing for the 2026 elections and working on establishing the \'Second Republic\'',
    'service.policy.label': 'CORE MISSION',
    'service.policy.text': 'Working towards the reforms needed in politics and society to build a stronger Bangladesh',

    // Dhaka-11 Section
    'dhaka11.label': 'MY CONSTITUENCY',
    'dhaka11.title.my': 'আমার',
    'dhaka11.title.dhaka11': 'Dhaka-11',
    'dhaka11.subtitle': 'Committed to serving the people of Dhaka-11 with transparency, accountability, and a vision for progressive development',
    'dhaka11.vision': 'Dhaka-11 is not just my constituency, it is my responsibility. Together, we will build a future where every voice is heard, every problem is addressed, and every dream has a chance to flourish.',
    'dhaka11.feature1.title': 'People-Centric Governance',
    'dhaka11.feature1.desc': 'Ensuring direct communication with constituents and solving local issues through community participation',
    'dhaka11.feature2.title': 'Infrastructure Development',
    'dhaka11.feature2.desc': 'Improving roads, drainage, public transportation, and urban planning for better quality of life',
    'dhaka11.feature3.title': 'Education & Youth Empowerment',
    'dhaka11.feature3.desc': 'Establishing modern educational facilities and skill development programs for young people',
    'dhaka11.feature4.title': 'Environmental Sustainability',
    'dhaka11.feature4.desc': 'Green spaces, pollution control, and sustainable urban development for a healthier Dhaka',
    'dhaka11.feature5.title': 'Healthcare Access',
    'dhaka11.feature5.desc': 'Quality healthcare facilities accessible to all residents regardless of economic status',
    'dhaka11.commitment': 'As your representative, I pledge to work tirelessly for the development and prosperity of Dhaka-11',
    'dhaka11.cta': 'Together for Dhaka-11',

    // Gallery Section
    'gallery.label': 'PHOTO GALLERY',
    'gallery.title.know': 'Know About',
    'gallery.title.nahid': 'Nahid Islam',
    'gallery.subtitle': 'A visual journey through the life, leadership, and legacy of Nahid Islam – from student activist to national leader',
    'gallery.category.all': 'All',
    'gallery.category.movement': 'Movement',
    'gallery.category.leadership': 'Leadership',
    'gallery.category.people': 'With People',
    'gallery.category.events': 'Events',
    'gallery.empty': 'No images found in this category',
    'gallery.item1.title': 'July Revolution Frontline',
    'gallery.item1.desc': 'Leading the student movement during the July 2024 uprising',
    'gallery.item2.title': 'Adviser to the Nation',
    'gallery.item2.desc': 'Serving as Posts, Telecommunications & IT Adviser',
    'gallery.item3.title': 'Meeting the People',
    'gallery.item3.desc': 'Engaging with citizens and listening to their concerns',
    'gallery.item4.title': 'Student Coordinator',
    'gallery.item4.desc': 'Coordinating the anti-discrimination student movement',
    'gallery.item5.title': 'NCP Formation',
    'gallery.item5.desc': 'Announcing the formation of National Citizens Party',
    'gallery.item6.title': 'Policy Briefing',
    'gallery.item6.desc': 'Presenting reform initiatives in the interim government',
    'gallery.item7.title': 'Dhaka-11 Campaign',
    'gallery.item7.desc': 'Connecting with constituents in Dhaka-11',
    'gallery.item8.title': 'Youth Engagement',
    'gallery.item8.desc': 'Inspiring the next generation of leaders',
    'gallery.item9.title': 'Unity in Struggle',
    'gallery.item9.desc': 'Standing together for a better Bangladesh',

    // Core Values Section
    'values.label': 'DEMOCRATIC VALUES',
    'values.title.upholding': 'Upholding',
    'values.title.freedom': 'Freedom',
    'values.title.accountability': '& Accountability',
    'values.subtitle': 'Building a Bangladesh grounded in free speech, justice for victims, and zero tolerance for corruption',
    'values.freedom.title': 'Freedom of Speech',
    'values.freedom.desc': 'After the uprising, we restored freedom of speech. Now we must use it with sincerity and responsibility to strengthen our democracy.',
    'values.freedom.quote': 'There will be no place for pro-India or pro-Pakistan politics in Bangladesh. We will build the state by prioritizing Bangladesh\'s interests above all.',
    'values.justice.title': 'Accountability & Justice',
    'values.justice.desc': 'Standing firm on accountability for crimes against humanity and disappearances. Justice delayed is justice denied.',
    'values.justice.quote': 'Starting the trial of those involved in disappearances is a government\'s victory. Justice must be served.',
    'values.accountability.title': 'Anti-Corruption',
    'values.accountability.desc': 'The previous governance allowed extortion to become entrenched. We must shift to a culture of accountability and transparency.',
    'values.accountability.quote': 'Corruption and extortion have no place in our new Bangladesh. Accountability starts now.',
    'values.cta.text': 'Stand with us for a transparent Bangladesh',
    'values.cta.button': 'Join the Movement',

    // Future Vision Section
    'future.label': 'THE NEXT CHAPTER',
    'future.title.the': 'The',
    'future.title.next': 'Next',
    'future.title.chapter': 'Chapter',
    'future.subtitle': 'From adviser to candidate – ready to contest in the upcoming national election and continue serving the people',
    'future.electoral.title': 'Electoral Ambition',
    'future.electoral.desc': 'After resigning as Adviser and submitting wealth statement, ready to contest in the national election as NCP (National Citizens Party) candidate for change.',
    'future.electoral.cta': 'Support Our Campaign',
    'future.electoral.secondary': 'Learn More',
    'future.commitment.item1.title': 'Transparent Leadership',
    'future.commitment.item1.desc': 'Full disclosure and accountability to the people',
    'future.commitment.item2.title': 'NCP Voice',
    'future.commitment.item2.desc': 'Representing National Citizens Party values and the people',
    'future.commitment.item3.title': 'Reform Champion',
    'future.commitment.item3.desc': 'Continuing the push for political and social reform',
    'future.pillars.title': 'Three Pillars of Our Campaign',
    'future.pillar1.title': 'Electoral Integrity',
    'future.pillar1.desc': 'Ensuring free, fair, and transparent elections for all',
    'future.pillar2.title': 'People\'s Movement',
    'future.pillar2.desc': 'The 2024 movement was the people\'s movement – we are merely its navigators',
    'future.pillar3.title': 'Prosperous Bangladesh',
    'future.pillar3.desc': 'Building economic opportunity and social justice for every citizen',
    'future.movement.quote': 'The one-point demand or government collapse must come from the people. When people make a final decision, only then comes the official announcement.',
    'future.movement.author': 'Nahid Islam on the July Revolution',

    // About Section
    'about.label': 'ABOUT NAHID ISLAM',
    'about.title.about': 'About',
    'about.title.nahid': 'Nahid Islam',
    'about.subtitle': 'From student activist to national leader — a journey of courage, conviction, and commitment to Bangladesh',
    'about.story.title': 'A Leader Forged in Movement',
    'about.story.para1': 'Nahid Islam emerged as one of the key coordinators of the July 2024 anti-discrimination student movement that led to the fall of an authoritarian regime. As a student of Sociology at Dhaka University, he became the voice of a generation demanding justice, equality, and democratic reforms.',
    'about.story.para2': 'Following the success of the movement, Nahid served as an Adviser in the interim government, overseeing Posts, Telecommunications & IT, and Information & Broadcasting ministries. He resigned to form the National Citizens Party (NCP), marking his transition from activist to political leader.',
    'about.quote': 'The struggle for a better Bangladesh is not mine alone — it belongs to every citizen who dreams of justice, equality, and prosperity.',
    'about.quote.author': 'Nahid Islam',
    'about.mission.title': 'My Mission',
    'about.mission.desc': 'To build a Bangladesh where every voice is heard, every citizen has equal opportunity, and transparent governance is the foundation of our democracy. Through the National Citizens Party, we will continue the fight for reforms and people-centric policies.',
    'about.journey.title': 'Journey of Leadership',
    'about.milestone1.year': '2024',
    'about.milestone1.title': 'Student Movement',
    'about.milestone1.desc': 'Led anti-discrimination student movement as key coordinator',
    'about.milestone2.year': 'August 2024',
    'about.milestone2.title': 'Adviser Position',
    'about.milestone2.desc': 'Served in interim government overseeing key ministries',
    'about.milestone3.year': 'February 2025',
    'about.milestone3.title': 'NCP Formation',
    'about.milestone3.desc': 'Founded National Citizens Party as Convener',
    'about.milestone4.year': '2026',
    'about.milestone4.title': 'Electoral Campaign',
    'about.milestone4.desc': 'Running for parliament from Dhaka-11 constituency',
    'about.values.title': 'Core Values',
    'about.value1.title': 'Integrity',
    'about.value1.desc': 'Leading with honesty, transparency, and accountability in all actions',
    'about.value2.title': 'People First',
    'about.value2.desc': 'Prioritizing the needs and voices of citizens above everything else',
    'about.value3.title': 'Reform Vision',
    'about.value3.desc': 'Committed to systemic reforms for a stronger, fairer Bangladesh',

    // Call to Action Section
    'cta.label': 'YOUR VOTE, OUR FUTURE',
    'cta.headline.part1': 'If You Want Reform,',
    'cta.headline.part2': 'Vote YES',
    'cta.subheadline': 'Let us make our struggle successful with public vote. A correct vote will ensure accountability and people\'s governance.',
    'cta.means': 'MEANS',
    'cta.represents': 'REPRESENTS',
    'cta.yes.label': 'VOTE YES',
    'cta.yes.title': 'হ্যাঁ',
    'cta.yes.means': 'Reform & Change',
    'cta.yes.point1': 'জবাবদিহিতা ও সুশাসন (Accountability & Good Governance)',
    'cta.yes.point2': 'যুব শক্তির জাগরণ (Awakening of Youth Power)',
    'cta.yes.point3': 'মেধাভিত্তিক সমাজ (Merit-based Society)',
    'cta.no.label': 'VOTE NO',
    'cta.no.title': 'না',
    'cta.no.means': 'Old System Maintained',
    'cta.no.point1': 'অস্বচ্ছতা ও দুর্নীতি (Opacity & Corruption)',
    'cta.no.point2': 'স্থবিরতা ও অব্যবস্থাপনা (Stagnation & Mismanagement)',
    'cta.no.point3': 'কোটা ও বৈষম্য (Quota & Discrimination)',
    'cta.button': 'Let\'s Stand for Change',
    'cta.footer': 'আপনার ভোট, আমাদের ভবিষ্যৎ (Your Vote, Our Future)',
    'cta.closing': 'সংস্কার চাইলে হ্যাঁ ভোট দিন'
  },
  bn: {
    // Navbar
    'nav.vision': 'ভিশন',
    'nav.platform': 'প্ল্যাটফর্ম',
    'nav.about': 'সম্পর্কে',
    'nav.news': 'সংবাদ',
    'nav.contact': 'যোগাযোগ',
    'nav.volunteer': 'স্বেচ্ছাসেবক',
    
    // Hero Section
    'hero.tagline': 'চলুন গড়ি নতুন বাংলাদেশ',
    'hero.tagline.mobile': 'নতুন বাংলাদেশ',
    'hero.name.first': 'নাহিদ',
    'hero.name.last': 'ইসলাম',
    'hero.vision.link': 'আমাদের ভিশন দেখুন',
    'hero.vision.link.mobile': 'ভিশন',
    'hero.vision.subtitle': 'ন্যায়সঙ্গত ও সমতাভিত্তিক সমাজের জন্য লড়াই করুন, "উজ্জ্বল আগামীর জন্য ভোট দিন।"',
    'hero.join': 'যোগ দিন',
    'hero.movement': 'আন্দোলনে',
    'hero.badge.join': 'যোগ দিন',
    'hero.badge.movement': 'আন্দোলনে',
    'hero.description.student': 'ছাত্র নেতা।',
    'hero.description.leader': 'বিপ্লবী।',
    'hero.description.candidate': 'জাতীয় নাগরিক পার্টি (এনসিপি) আহবায়ক।',
    'hero.independent': 'জাতীয় নাগরিক পার্টি (এনসিপি)',
    'hero.constituency': 'ঢাকা-১১',
    
    // Vision Section
    'vision.label': 'আমাদের ভিশন',
    'vision.title.new': 'নতুন',
    'vision.title.bangladesh': 'বাংলাদেশ',
    'vision.title.starts': 'শুরু এখান থেকে',
    'vision.subtitle': 'একসাথে, আমরা এমন একটি নির্বাচনী এলাকা গড়ে তুলব যা ছাত্র, শ্রমিক এবং পরিবারের কণ্ঠস্বর প্রতিনিধিত্ব করে যারা স্বচ্ছ, জবাবদিহিমূলক নেতৃত্বে বিশ্বাস করে।',
    'vision.card1.title': 'ন্যায়বিচার ও সমতা',
    'vision.card1.desc': 'এমন একটি সমাজ গড়ে তোলা যেখানে প্রতিটি নাগরিকের সমান অধিকার এবং সুযোগ রয়েছে',
    'vision.card2.title': 'শিক্ষা সংস্কার',
    'vision.card2.desc': 'ভবিষ্যতের জন্য শিক্ষার্থীদের প্রস্তুত করতে আমাদের শিক্ষা ব্যবস্থার আধুনিকীকরণ',
    'vision.card3.title': 'যুব ক্ষমতায়ন',
    'vision.card3.desc': 'তরুণ নেতাদের জন্য আমাদের জাতি গঠনের পথ তৈরি করা',
    'vision.card4.title': 'অর্থনৈতিক প্রবৃদ্ধি',
    'vision.card4.desc': 'সমৃদ্ধি তৈরিতে উদ্যোক্তা এবং ছোট ব্যবসার সমর্থন',
    'vision.card5.title': 'স্বাস্থ্যসেবা প্রবেশাধিকার',
    'vision.card5.desc': 'সকল সম্প্রদায়ের জন্য মানসম্পন্ন স্বাস্থ্যসেবা নিশ্চিত করা',
    'vision.card6.title': 'উদ্ভাবন কেন্দ্র',
    'vision.card6.desc': 'ঢাকা-১০ কে প্রযুক্তি এবং উদ্ভাবনের কেন্দ্রে রূপান্তরিত করা',
    'vision.cta.label': 'পরিবর্তনে অংশ নিতে প্রস্তুত?',
    'vision.cta.title': 'আজই আমাদের প্রচারণায় যোগ দিন',
    'vision.cta.button': 'জড়িত হন',

    // July Revolution Section
    'july.label': 'জুলাই বিপ্লব',
    'july.title.the': '',
    'july.title.architect': 'পরিবর্তনের',
    'july.title.change': 'স্থপতি',
    'july.subtitle': 'জুলাই ২০২৪ বিপ্লবের সূচনাকারী বৈষম্যবিরোধী ছাত্র আন্দোলনের নেতৃত্ব দিয়েছেন',
    'july.role.title': 'প্রধান সমন্বয়কারী',
    'july.role.desc': 'জুলাই বিপ্লবের সময় বৈষম্যবিরোধী ছাত্র আন্দোলনের নেতৃত্ব দিয়েছেন',
    'july.movement.title': 'গণঅভ্যুত্থান',
    'july.movement.desc': 'কোটা সংস্কার প্রতিবাদ থেকে ইতিহাস পরিবর্তনকারী আন্দোলন',
    'july.book.label': 'সামনের সারি থেকে',
    'july.book.title': 'জুলাই: জন্মভূমি অথবা মৃত্যু',
    'july.book.desc': 'জুলাই ২০২৪-এর সংগ্রাম, ত্যাগ এবং মুক্তির চেতনার প্রথম হাতের বিবরণ।',
    'july.book.cta': 'আরও পড়ুন',
    'july.quote.text': 'আমরাই আমাদের সীমান্ত রক্ষা করবো। সীমান্তে আর কোনো আগ্রাসন আমরা মেনে নেব না।',
    'july.quote.author': 'নাহিদ ইসলাম',
    'july.struggle.title': 'ত্যাগের পথ',
    'july.struggle.detention.title': 'আটক',
    'july.struggle.detention.desc': 'ন্যায়বিচারের জন্য লড়াই করার সময় বেআইনি আটকের মুখোমুখি',
    'july.struggle.torture.title': 'শারীরিক ও মানসিক নির্যাতন',
    'july.struggle.torture.desc': 'উদ্দেশ্যের জন্য চরম পরিস্থিতি সহ্য করেছেন',
    'july.struggle.surveillance.title': 'কঠোর নজরদারি',
    'july.struggle.surveillance.desc': 'ক্রমাগত পর্যবেক্ষণ সত্ত্বেও আন্দোলন অব্যাহত রেখেছেন',
    'july.struggle.liberation.title': 'জনগণের মুক্তি',
    'july.struggle.liberation.desc': 'সম্মিলিত ত্যাগের মাধ্যমে বিজয় অর্জন',

    // Public Service Section
    'service.label': 'জনসেবা',
    'service.title.public': 'জনসেবা',
    'service.title.service': 'ও নেতৃত্ব',
    'service.subtitle': 'অন্তর্বর্তী সরকারে উপদেষ্টা হিসেবে দায়িত্ব পালন (আগস্ট ২০২৪ – ফেব্রুয়ারি ২০২৫), একাধিক মন্ত্রণালয়ে সংস্কার চালনা',
    'service.role1.title': 'ডাক, টেলিযোগাযোগ ও তথ্যপ্রযুক্তি উপদেষ্টা',
    'service.role1.period': 'আগস্ট ২০২৪ – ফেব্রুয়ারি ২০২৫',
    'service.role1.desc': 'মোবাইল ইন্টারনেট ও সেবার ওপর কর কমিয়ে সাধারণ মানুষের জন্য ইন্টারনেট সস্তা করার উদ্যোগ নেন এবং ডিজিটাল বৈষম্য দূর করতে কাজ করেন',
    'service.role2.title': 'তথ্য ও সম্প্রচার উপদেষ্টা',
    'service.role2.period': 'আগস্ট ২০২৪ – ফেব্রুয়ারি ২০২৫',
    'service.role2.desc': 'বাংলাদেশে দীর্ঘদিনের সেন্সরশিপ প্রথার আমূল সংস্কার করেন এবং চলচ্চিত্র নির্মাতাদের দাবির প্রেক্ষিতে \'বাংলাদেশ চলচ্চিত্র সার্টিফিকেশন বোর্ড\' গঠন করেন',
    'service.role3.title': 'আহবায়ক, জাতীয় নাগরিক পার্টি (NCP)',
    'service.role3.period': 'ফেব্রুয়ারি ২০২৫ – বর্তমান',
    'service.role3.desc': 'সরকার থেকে পদত্যাগ করে নতুন রাজনৈতিক দল গঠন করেন এবং বর্তমানে ২০২৬ সালের নির্বাচনের প্রস্তুতি ও \'দ্বিতীয় প্রজাতন্ত্র\' প্রতিষ্ঠার রূপরেখা নিয়ে কাজ করছেন',
    'service.policy.label': 'মূল লক্ষ্য',
    'service.policy.text': 'একটি শক্তিশালী বাংলাদেশ গড়তে রাজনীতি ও সমাজে প্রয়োজনীয় সংস্কারের জন্য কাজ করছি',

    // Dhaka-11 Section
    'dhaka11.label': 'আমার নির্বাচনী এলাকা',
    'dhaka11.title.my': 'আমার',
    'dhaka11.title.dhaka11': 'ঢাকা-১১',
    'dhaka11.subtitle': 'স্বচ্ছতা, জবাবদিহিতা এবং প্রগতিশীল উন্নয়নের দৃষ্টিভঙ্গি নিয়ে ঢাকা-১১ এর মানুষের সেবা করতে প্রতিশ্রুতিবদ্ধ',
    'dhaka11.vision': 'ঢাকা-১১ শুধু আমার নির্বাচনী এলাকা নয়, এটি আমার দায়িত্ব। একসাথে আমরা এমন একটি ভবিষ্যৎ গড়ব যেখানে প্রতিটি কণ্ঠস্বর শোনা হয়, প্রতিটি সমস্যার সমাধান করা হয় এবং প্রতিটি স্বপ্ন বাস্তবায়নের সুযোগ পায়।',
    'dhaka11.feature1.title': 'জনকেন্দ্রিক শাসন',
    'dhaka11.feature1.desc': 'নির্বাচনী এলাকার মানুষের সাথে সরাসরি যোগাযোগ এবং সম্প্রদায়ের অংশগ্রহণের মাধ্যমে স্থানীয় সমস্যার সমাধান',
    'dhaka11.feature2.title': 'অবকাঠামো উন্নয়ন',
    'dhaka11.feature2.desc': 'জীবনযাত্রার মান উন্নতির জন্য রাস্তাঘাট, নিষ্কাশন, গণপরিবহন এবং নগর পরিকল্পনার উন্নয়ন',
    'dhaka11.feature3.title': 'শিক্ষা ও যুব ক্ষমতায়ন',
    'dhaka11.feature3.desc': 'তরুণদের জন্য আধুনিক শিক্ষা প্রতিষ্ঠান এবং দক্ষতা উন্নয়ন কর্মসূচি প্রতিষ্ঠা',
    'dhaka11.feature4.title': 'পরিবেশগত স্থায়িত্ব',
    'dhaka11.feature4.desc': 'সুস্থ ঢাকার জন্য সবুজ এলাকা, দূষণ নিয়ন্ত্রণ এবং টেকসই নগর উন্নয়ন',
    'dhaka11.feature5.title': 'স্বাস্থ্যসেবা প্রবেশাধিকার',
    'dhaka11.feature5.desc': 'অর্থনৈতিক অবস্থা নির্বিশেষে সকল বাসিন্দার জন্য মানসম্পন্ন স্বাস্থ্যসেবা সুবিধা',
    'dhaka11.commitment': 'আপনার প্রতিনিধি হিসেবে, আমি ঢাকা-১১ এর উন্নয়ন ও সমৃদ্ধির জন্য নিরলসভাবে কাজ করার অন্গীকার করছি',
    'dhaka11.cta': 'একসাথে ঢাকা-১১ এর জন্য',

    // Gallery Section
    'gallery.label': 'ফটো গ্যালারি',
    'gallery.title.know': 'জানুন',
    'gallery.title.nahid': 'নাহিদ ইসলামকে',
    'gallery.subtitle': 'ছাত্র আন্দোলনকারী থেকে জাতীয় নেতা – নাহিদ ইসলামের জীবন, নেতৃত্ব এবং উত্তরাধিকারের একটি দৃশ্যমান যাত্রা',
    'gallery.category.all': 'সব',
    'gallery.category.movement': 'আন্দোলন',
    'gallery.category.leadership': 'নেতৃত্ব',
    'gallery.category.people': 'জনগণের সাথে',
    'gallery.category.events': 'অনুষ্ঠান',
    'gallery.empty': 'এই বিভাগে কোন ছবি পাওয়া যায়নি',
    'gallery.item1.title': 'জুলাই বিপ্লবের সামনে সারিতে',
    'gallery.item1.desc': 'জুলাই ২০২৪ গণঅভ্যুত্থানে ছাত্র আন্দোলনের নেতৃত্ব',
    'gallery.item2.title': 'জাতির উপদেষ্টা',
    'gallery.item2.desc': 'ডাক, টেলিযোগাযোগ ও তথ্যপ্রযুক্তি উপদেষ্টা হিসেবে সেবা',
    'gallery.item3.title': 'জনগণের সাথে সাক্ষাৎ',
    'gallery.item3.desc': 'নাগরিকদের সাথে যুক্ত হওয়া এবং তাদের কথা শোনা',
    'gallery.item4.title': 'ছাত্র সমন্বয়ক',
    'gallery.item4.desc': 'বৈষম্যবিরোধী ছাত্র আন্দোলনের সমন্বয়',
    'gallery.item5.title': 'এনসিপি গঠন',
    'gallery.item5.desc': 'জাতীয় নাগরিক পার্টি গঠনের ঘোষণা',
    'gallery.item6.title': 'নীতি ব্রিফিং',
    'gallery.item6.desc': 'অন্তর্বর্তী সরকারে সংস্কার উদ্যোগ উপস্থাপন',
    'gallery.item7.title': 'ঢাকা-১১ প্রচারাভিযান',
    'gallery.item7.desc': 'ঢাকা-১১ এর নির্বাসিতদের সাথে যোগাযোগ',
    'gallery.item8.title': 'যুব যুক্ততা',
    'gallery.item8.desc': 'পরবর্তী প্রজন্মের নেতাদের অনুপ্রাণিত করা',
    'gallery.item9.title': 'সংগ্রামে একতা',
    'gallery.item9.desc': 'একটি ভাল বাংলাদেশের জন্য একসাথে দাঁড়ানো',

    // Core Values Section
    'values.label': 'গণতান্ত্রিক মূল্যবোধ',
    'values.title.upholding': 'রক্ষা করছি',
    'values.title.freedom': 'স্বাধীনতা',
    'values.title.accountability': 'ও জবাবদিহিতা',
    'values.subtitle': 'মুক্ত বাক, ভুক্তভোগীদের জন্য ন্যায়বিচার এবং দুর্নীতির প্রতি শূন্য সহনশীলতার ভিত্তিতে বাংলাদেশ গড়া',
    'values.freedom.title': 'বাকস্বাধীনতা',
    'values.freedom.desc': 'অভ্যুত্থানের পর, আমরা বাকস্বাধীনতা ফিরিয়ে এনেছি। এখন আমাদের গণতন্ত্রকে শক্তিশালী করতে আন্তরিকতা এবং দায়িত্বশীলতার সাথে এটি ব্যবহার করতে হবে।',
    'values.freedom.quote': 'বাংলাদেশে প্রো-ইন্ডিয়ান বা প্রো-পাকিস্তানি রাজনীতির কোনো জায়গা থাকবে না। আমরা বাংলাদেশের স্বার্থকে সবার আগে রেখে রাষ্ট্র গঠন করব।',
    'values.justice.title': 'জবাবদিহিতা ও ন্যায়বিচার',
    'values.justice.desc': 'মানবতাবিরোধী অপরাধ এবং গুম এর জন্য জবাবদিহিতায় দৃঢ় অবস্থান। বিলম্বিত ন্যায়বিচার অস্বীকৃত ন্যায়বিচার।',
    'values.justice.quote': 'গুমের সাথে জড়িতদের বিচার শুরু করা সরকারের বিজয়। ন্যায়বিচার নিশ্চিত করতে হবে।',
    'values.accountability.title': 'দুর্নীতিবিরোধী',
    'values.accountability.desc': 'পূর্ববর্তী শাসন চাঁদাবাজিকে প্রাতিষ্ঠানিক হতে দিয়েছিল। আমাদের জবাবদিহিতা এবং স্বচ্ছতার সংস্কৃতিতে পরিবর্তন আনতে হবে।',
    'values.accountability.quote': 'দুর্নীতি এবং চাঁদাবাজির আমাদের নতুন বাংলাদেশে কোনো স্থান নেই। জবাবদিহিতা এখনই শুরু।',
    'values.cta.text': 'স্বচ্ছ বাংলাদেশের জন্য আমাদের সাথে দাঁড়ান',
    'values.cta.button': 'আন্দোলনে যোগ দিন',

    // Future Vision Section
    'future.label': 'পরবর্তী অধ্যায়',
    'future.title.the': '',
    'future.title.next': 'পরবর্তী',
    'future.title.chapter': 'অধ্যায়',
    'future.subtitle': 'উপদেষ্টা থেকে প্রার্থী – আসন্ন জাতীয় নির্বাচনে প্রতিদ্বন্দ্বিতা করতে এবং জনগণের সেবা চালিয়ে যেতে প্রস্তুত',
    'future.electoral.title': 'নির্বাচনী উচ্চাকাঙ্ক্ষা',
    'future.electoral.desc': 'উপদেষ্টা হিসেবে পদত্যাগ এবং সম্পদের বিবরণী জমা দেওয়ার পর, পরিবর্তনের জন্য জাতীয় নাগরিক পার্টি (এনসিপি) প্রার্থী হিসেবে জাতীয় নির্বাচনে প্রতিদ্বন্দ্বিতা করতে প্রস্তুত।',
    'future.electoral.cta': 'আমাদের প্রচারণা সমর্থন করুন',
    'future.electoral.secondary': 'আরও জানুন',
    'future.commitment.item1.title': 'স্বচ্ছ নেতৃত্ব',
    'future.commitment.item1.desc': 'জনগণের কাছে সম্পূর্ণ প্রকাশ এবং জবাবদিহিতা',
    'future.commitment.item2.title': 'এনসিপি কণ্ঠস্বর',
    'future.commitment.item2.desc': 'জাতীয় নাগরিক পার্টির মূল্যবোধ এবং জনগণের প্রতিনিধিত্ব',
    'future.commitment.item3.title': 'সংস্কার চ্যাম্পিয়ন',
    'future.commitment.item3.desc': 'রাজনৈতিক এবং সামাজিক সংস্কারের জন্য চাপ অব্যাহত',
    'future.pillars.title': 'আমাদের প্রচারণার তিনটি স্তম্ভ',
    'future.pillar1.title': 'নির্বাচনী সততা',
    'future.pillar1.desc': 'সকলের জন্য মুক্ত, সুষ্ঠু এবং স্বচ্ছ নির্বাচন নিশ্চিত করা',
    'future.pillar2.title': 'জনগণের আন্দোলন',
    'future.pillar2.desc': '২০২৪ আন্দোলন ছিল জনগণের আন্দোলন – আমরা কেবল এর দিকনির্দেশক',
    'future.pillar3.title': 'সমৃদ্ধ বাংলাদেশ',
    'future.pillar3.desc': 'প্রতিটি নাগরিকের জন্য অর্থনৈতিক সুযোগ এবং সামাজিক ন্যায়বিচার গড়া',
    'future.movement.quote': 'এক দফা বা সরকার পতনের বিষয়টি জনগণের ভেতর থেকে আসতে হয়। মানুষ যখন চূড়ান্তভাবে সিদ্ধান্ত নিয়ে নেয়, তখনই আনুষ্ঠানিক ঘোষণা আসে।',
    'future.movement.author': 'জুলাই বিপ্লবে নাহিদ ইসলাম',

    // About Section
    'about.label': 'নাহিদ ইসলাম সম্পর্কে',
    'about.title.about': 'পরিচয়',
    'about.title.nahid': 'নাহিদ ইসলাম',
    'about.subtitle': 'ছাত্র আন্দোলনকারী থেকে জাতীয় নেতা — সাহস, দৃঢ়তা এবং বাংলাদেশের প্রতি প্রতিশ্রুতির এক যাত্রা',
    'about.story.title': 'আন্দোলনে গড়া এক নেতা',
    'about.story.para1': 'নাহিদ ইসলাম জুলাই ২০২৪ বৈষম্যবিরোধী ছাত্র আন্দোলনের অন্যতম প্রধান সমন্বয়ক হিসেবে উদ্ভূত হন, যা একটি কর্তৃত্ববাদী শাসনের পতনের দিকে নিয়ে যায়। ঢাকা বিশ্ববিদ্যালয়ের সমাজবিজ্ঞান বিভাগের ছাত্র হিসেবে, তিনি ন্যায়বিচার, সমতা এবং গণতান্ত্রিক সীসকার দাবি করা এক প্রজন্মের কণ্ঠস্বর হয়ে ওঠেন।',
    'about.story.para2': 'আন্দোলনের সফলতার পর, নাহিদ অন্তর্বর্তী সরকারে উপদেষ্টা হিসেবে কাজ করেন, ডাক, টেলিযোগাযোগ ও তথ্যপ্রযুক্তি, এবং তথ্য ও সম্প্রচার মন্ত্রণালয়ের তদারকি করেন। তিনি জাতীয় নাগরিক পার্টি (NCP) গঠনের জন্য পদত্যাগ করেন, যা আন্দোলনকারী থেকে রাজনীতিক নেতার রূপান্তর চিহ্নিত করে।',
    'about.quote': 'একটি ভাল বাংলাদেশের জন্য সংগ্রাম শুধু আমার নয় — এটি প্রতিটি নাগরিকের যারা ন্যায়বিচার, সমতা এবং সমৃদ্ধির স্বপ্ন দেখেন।',
    'about.quote.author': 'নাহিদ ইসলাম',
    'about.mission.title': 'আমার লক্ষ্য',
    'about.mission.desc': 'এমন একটি বাংলাদেশ গড়া যেখানে প্রতিটি কণ্ঠস্বর শোনা হয়, প্রতিটি নাগরিকের সমান সুযোগ থাকে এবং স্বচ্ছ শাসন আমাদের গণতন্ত্রের ভিত্তি। জাতীয় নাগরিক পার্টির মাধ্যমে, আমরা সংসকার এবং জনকেন্দ্রিক নীতির জন্য লড়াই চালিয়ে যাব।',
    'about.journey.title': 'নেতৃত্বের যাত্রা',
    'about.milestone1.year': '২০২৪',
    'about.milestone1.title': 'ছাত্র আন্দোলন',
    'about.milestone1.desc': 'প্রধান সমন্বয়ক হিসেবে বৈষম্যবিরোধী ছাত্র আন্দোলনের নেতৃত্ব',
    'about.milestone2.year': 'আগস্ট ২০২৪',
    'about.milestone2.title': 'উপদেষ্টা পদ',
    'about.milestone2.desc': 'অন্তর্বর্তী সরকারে প্রধান মন্ত্রণালয়গুলির তদারকি',
    'about.milestone3.year': 'ফেব্রুয়ারি ২০২৫',
    'about.milestone3.title': 'এনসিপি গঠন',
    'about.milestone3.desc': 'আহবায়ক হিসেবে জাতীয় নাগরিক পার্টি প্রতিষ্ঠা',
    'about.milestone4.year': '২০২৬',
    'about.milestone4.title': 'নির্বাচনী প্রচারাভিযান',
    'about.milestone4.desc': 'ঢাকা-১১ নির্বাচনী এলাকা থেকে সংসদ সদস্য পদে প্রতিদ্বন্দ্বিতা',
    'about.values.title': 'মূল মূল্যবোধ',
    'about.value1.title': 'সত্যনিষ্ঠা',
    'about.value1.desc': 'সকল কাজে সৎয়তা, স্বচ্ছতা এবং জবাবদিহিতা সহ নেতৃত্ব',
    'about.value2.title': 'জনগণ প্রথম',
    'about.value2.desc': 'সব কিছুর উপরে নাগরিকদের চাহিদা এবং কণ্ঠস্বরকে অগ্রাধিকার দেওয়া',
    'about.value3.title': 'সংসকার দৃষ্টি',
    'about.value3.desc': 'একটি শক্তিশালী, ন্যায়সঙ্গত বাংলাদেশের জন্য ব্যবস্থাগত সংসকারে প্রতিশ্রুতিবদ্ধ',

    // Call to Action Section
    'cta.label': 'আপনার ভোট, আমাদের ভবিষ্যৎ',
    'cta.headline.part1': 'সংস্কার চাইলে',
    'cta.headline.part2': 'হ্যাঁ ভোট দিন',
    'cta.subheadline': 'আসুন, আমাদের সংগ্রামকে জনরায় দিয়ে সফল করি। একটি সঠিক ভোট নিশ্চিত করবে জবাবদিহিতা ও জনগণের শাসন।',
    'cta.means': 'অর্থ',
    'cta.represents': 'প্রতিনিধিত্ব করে',
    'cta.yes.label': 'হ্যাঁ ভোট',
    'cta.yes.title': 'হ্যাঁ',
    'cta.yes.means': 'সংস্কার ও পরিবর্তন',
    'cta.yes.point1': 'জবাবদিহিতা ও সুশাসন (Accountability & Good Governance)',
    'cta.yes.point2': 'যুব শক্তির জাগরণ (Awakening of Youth Power)',
    'cta.yes.point3': 'মেধাভিত্তিক সমাজ (Merit-based Society)',
    'cta.no.label': 'না ভোট',
    'cta.no.title': 'না',
    'cta.no.means': 'পুরনো ব্যবস্থা বহাল',
    'cta.no.point1': 'অস্বচ্ছতা ও দুর্নীতি (Opacity & Corruption)',
    'cta.no.point2': 'স্থবিরতা ও অব্যবস্থাপনা (Stagnation & Mismanagement)',
    'cta.no.point3': 'কোটা ও বৈষম্য (Quota & Discrimination)',
    'cta.button': 'আসুন, পরিবর্তনের পক্ষে দাঁড়াই',
    'cta.footer': 'আপনার ভোট, আমাদের ভবিষ্যৎ (Your Vote, Our Future)',
    'cta.closing': 'সংস্কার চাইলে হ্যাঁ ভোট দিন'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('bn');

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations.en];
    // Return translation even if it's an empty string (only fallback to key if undefined)
    return translation !== undefined ? translation : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}